name: vulncheck-GitHubAction-example

on:
  pull_request:
    branches:
    - master

permissions: write-all

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: VulnCheck Action
        uses: vulncheck-oss/action@v1.1.3
        with:
          token: ${{ secrets.VC_TOKEN }}
          command: scan
          scan-path: ./
